CONFIG_ZMK_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_SELF=y

CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=75
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=15
